# Generated by Django 4.1.2 on 2022-10-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
    ]
