# Generated by Django 4.1.2 on 2022-10-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_rename_semester_semester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='course_in_semester', to='attendance.course'),
        ),
    ]
