# Generated by Django 4.1.2 on 2022-10-20 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_semester_courses_alter_class_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.lecturer'),
        ),
    ]
