# Generated by Django 4.1.2 on 2022-10-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_class_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='enrollment',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_student', to='attendance.student'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='students',
            field=models.ManyToManyField(related_name='student_attended', to='attendance.student'),
        ),
    ]
