# Generated by Django 4.1.2 on 2022-10-21 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_class_enrollment_collegeday_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='enrollment',
        ),
        migrations.AlterField(
            model_name='collegeday',
            name='collegeclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_collegeday', to='attendance.class'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
