# Generated by Django 4.1.2 on 2022-10-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeday',
            name='students',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField()),
                ('collegeday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.collegeday')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
