# Generated by Django 4.1.2 on 2022-10-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_remove_collegeday_students_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeday',
            old_name='date',
            new_name='collegedate',
        ),
        migrations.AlterField(
            model_name='collegeday',
            name='collegeclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class'),
        ),
    ]
