# Generated by Django 4.1.2 on 2022-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_rename_date_collegeday_collegedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_student', to='attendance.student'),
        ),
        migrations.AddField(
            model_name='collegeday',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='collegeday_student', to='attendance.student'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
