# Generated by Django 4.1.2 on 2022-10-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
