# Generated by Django 4.1.2 on 2022-10-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_alter_lecturer_dob_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
